### ISSUE TITLE
Building with NAG Fortran compiler

### ISSUE THREAD

**Issue by wadudmiah** [koenpoppe/ErrorHandlingInFortran2003#1]
Hello, how do I build with the NAG Fortran compiler? If I set:
`FC=nagfor_beta`
it obviously complains that the `nagfor_beta` command cannot be found. If I set:
`FC=nagfor`
then it does not set the compilation flags.

**Comment by wadudmiah** [comment]
replaced "nagfor_beta" with "nagfor" and set FC=nagfor

**Comment by koenpoppe** [comment]
Fixed in 6d116bd7996f1df85a2b214ba9b0345f2d909af6. The _beta suffix shouldn't be there.
