### ISSUE TITLE
Unable to build with NAG compiler

### ISSUE THREAD

**Issue by wadudmiah** [koenpoppe/ErrorHandlingInFortran2003#2]
I am getting the following error message when I try to build with the NAG compiler:

`nagfor -c -colour -v -fpp -O0 -C=all -g90 -DFC_FIXED_LENGTH_CHARACTERSTRINGS -DFC_NO_ALLOCATABLE_DTCOMP -DFC_NO_DT_CONSTRUCTOR  -mdir nagfor_build/ -I nagfor_build/ error_handling_error.f03
NAG Fortran Compiler Release 6.2(Chiyoda) Build 6208
error_handling_error.f03:
Error: error_handling_error.f03, line 210: Rank 0 type ERROR result variable of pure function EMPTY_ERROR will invoke an impure final subroutine
Errors in declarations, no further processing for EMPTY_ERROR
[NAG Fortran Compiler error termination, 1 error]
make: *** [Makefile:45: error_handling_error.o] Error 2
[wadudm@wm-porlock ~/ErrorHandlingInFortran2003/Framework]$ `

I am not knowledgeable with OOP, so don't know how to help :-(

**Comment by wadudmiah** [comment]
This is with version 6.2 of the NAG compiler

**Comment by koenpoppe** [comment]
Fixed in 17057f5789c07c06327632e9333a3c48d6ca4910. This wasn't a compiler error in NAGFOR 5.3.
